### PR TITLE
Fix console integration issues

### PR DESCRIPTION
**Pull request by sub-mod**
fixed multiple issues seen in Oshinko Console code ::
- [x] Add custom Angular module 
- [x] Add hawtioPluginLoader to load
- [x] Re-order run method to register extensions
- [x] add the correct oshinkoUrl for routes to work 
- [x] add the correct templateUrl for the views folder 
- [x] Fix oshinkoConsoleTemplates for grunt to add views to templateCache
- [x] Remove ng-click to avoid page fresh issue
- [x] Rename files as per review comments from openshift folks
- [x] Rename Controllers/TemplateUrl as per review comments from openshift folks

### CODE REVIEW

**Comment by tmckayus** [comment]
lgtm but js is not my strength :)

**Comment by crobby** [comment]
Currently seeing the following in my dev env....

Error: [$injector:nomod] Module 'oshinkoConsole' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.20/$injector/nomod?p0=oshinkoConsole

**Comment by crobby** [comment]
Also, grunt build bails with a warning at the moment.
Running "cssmin:generated" (cssmin) task
Warning: Path must be a string. Received undefined Use --force to continue.

Aborted due to warnings.

Ok, the above ^^ must be something in my env.  Another machine works for me.

**Comment by sub-mod** [comment]
https://paste.fedoraproject.org/462386/77664415/
I don't see a build failure.

**Pull request merged**
