### PR TITLE
create zip/tar release files

### PR DESCRIPTION
**Pull request by sub-mod**

### CODE REVIEW

**Comment by elmiko** [comment]
tested locally, this worked for me

**Review by crobby — APPROVED** [review]
Should we add a .gitignore for these new files (and maybe even some others?

**Comment by crobby** [comment]
I have also tested this and it works for me.

**Comment by elmiko** [comment]
> Should we add a .gitignore for these new files (and maybe even some others?

+1

**Review by crobby — DISMISSED** [review]
Ok, I'll "request changes" instead of approve.  I'd like to see a .gitignore added and it should include the 2 files generated by this change.

**Comment by elmiko** [comment]
we might just need to have a blanket catch-all for `*.zip` and `*.tar`, it could be tough to ignore the specific file names due to the version component.

one question, should we have the tar file compressed as well?

**Pull request merged**
